### DISCUSSION TITLE
Discuss YUMEMI Inc.'s recommended lint rules.

### DISCUSSION THREAD

**Discussion by blendthink** [yumemi-inc/flutter-yumemi-lints#33] [Ideas]
I'd like to follow the example of the FlutterKaigi/2023 repository and include all lint rules while gradually disabling unnecessary ones.

https://github.com/FlutterKaigi/2023/blob/main/analysis_options.yaml

**Comment by blendthink** [comment]
I will configure the `language` and `errors` settings in the `analyzer` section as follows:

```yaml
analyzer:
  language:
    # Increase safety as much as possible.
    strict-casts: true
    strict-inference: true
    strict-raw-types: true
  errors:
    # By including all.yaml, some rules will conflict. 
    # These warnings will be addressed within this file.
    included_file_warning: ignore
```

How about that?

**Comment by blendthink** [comment]
I will configure the `rules` settings in the `linter` section as follows:

```yaml
linter:
  rules:
    # Conflicts with enabling `strict-raw-types`.
    avoid_annotating_with_dynamic: false

    # Conflicts with enabling `avoid_types_on_closure_parameters`, `omit_local_variable_types`.
    always_specify_types: false

    # Conflicts with enabling `avoid_final_parameters`.
    prefer_final_parameters: false

    # Conflicts with enabling `always_use_package_imports`.
    prefer_relative_imports: false

    # Conflicts with enabling `prefer_single_quotes`.
    prefer_double_quotes: false

    # Conflicts with enabling `prefer_final_locals`.
    unnecessary_final: false

    # Using `=>` has sometimes to reduce readability.
    prefer_expression_function_bodies: false

    # Don't use Flutter-style todos.
    flutter_style_todos: false

    # There are cases that are warned but not fixed by `dart fix`.
    cascade_invocations: false

    # May add more methods later.
    one_member_abstracts: false

    # Don't often develop package.
    public_member_api_docs: false
```

How about that?
