### ISSUE TITLE
[Improve]: Change the warning level of `invalid_use_of_visible_for_testing_member` to error

### ISSUE THREAD

**Issue by blendthink** [yumemi-inc/flutter-yumemi-lints#87]
### Describe

```yaml:analysis_options.yaml
analyzer:
  errors:
    invalid_use_of_visible_for_testing_member: error
```

https://dart.dev/tools/diagnostic-messages#invalid_use_of_visible_for_testing_member

### Screenshots

N/A

### Environment

- Commit SHA: 649b386248326be6ffc78570f49133c1a0a0649c
